// Try & Catch

const number1 = 20;
const number3 = 30;

console.log(number1);

try {
    console.log(number2);
} catch (error) {
    console.log(error);
}

console.log(number3);
